version: 2
jobs:
  build:
    docker:
      -
        image: 'php:7.3.7'
      -
        image: "circleci/mysql:8.0.16\nenvironment:\n MYSQL_ROOT_PASSWORD: rootpw\n MYSQL_DATABASE: test_db\n MYSQL_USER: user\n MYSQL_PASSWORD: passw0rd"
    working_directory: ~/laravel
    steps:
      - checkout
      -
        run:
          name: 'Install MySQL CLI; Import dummy data;'
          command: "sudo apt-get install mysql-client\nmysql -h 127.0.0.1 -u user -ppassw0rd test_db < database/dummy.sql\"\n"
      -
        run:
          name: 'Setup Laravel testing environment variables for CircleCI test'
          command: 'cp .env.testing .env'
      -
        run:
          name: 'Update composer to latest version'
          command: 'composer self-update'
      -
        restore_cache:
          keys:
            - 'composer-v1-{{ checksum "composer.json" }}'
            - composer-v1-
      -
        run: 'composer install -n --prefer-dist --ignore-platform-reqs'
      -
        save_cache:
          key: 'composer-v1-{{ checksum "composer.json" }}'
          paths:
            - vendor
      -
        run:
          name: 'Migrate Laravel Database'
          command: 'php artisan migrate --env=testing --force'
      -
        run:
          name: 'Run Laravel Server'
          command: 'php artisan serve'
          background: true
      -
        run:
          name: 'Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing'
          command: vendor/bin/phpunit
