# PHP CircleCI 2.0 configuration file for Laravel 5.5 and Laravel Dusk by Wes Mahler
# Author wesmahler.com
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # - image: circleci/php:7.3.7
      - image: php:7.3.7-node-browsers
      - image: circleci/mysql:8.0.16
    working_directory: ~/laravel
    steps:
      - checkout

      - run:
         name: Install PHP sqlite and nodejs 6
         command: sudo apt-get install -y libsqlite3-dev nodejs

      - run:
         name: Setup Laravel testing environment variables for CircleCI test
         command: cp .env.testing .env

      - run:
         name: Update composer to latest version
         command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
         name: Migrate Laravel Database
         command: php artisan migrate --env=testing --force

      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true

      - run:
         name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
         command: vendor/bin/phpunit

